server:
  port: 8080
  context-path: /eShopApplet

spring:
  datasource:
    username: root
    password: hypertechpwd
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.54.123.188:3306/eshop_applet?useUnicode=true&characterEncoding=utf-8

mybatis:
  type-aliases-package: com.hypertech.applet.eshop.entity
  mapper-locations: classpath:mybatis/mapper/*.xml